#!/usr/bin/env python
# vim: set fileencoding=utf8 :

import herbstluft
import subprocess

with herbstluft.HerbstluftChain() as hc:
    #we want alt as our mod. mod4 would give us the super(windows) key
    mod=herbstluft.mod1
    shift=herbstluft.shift
    enter=herbstluft.enter
    control=herbstluft.control
    tab=herbstluft.tab

    #let the daemons know that the autostart file is being reloaded
    hc.emit_hook('reload')

    #lock it to speed things up
    hc.lock()

    #reset keybindings then set them up
    hc.keyunbind('all')
    hc.keybind(mod+shift+'q','close')
    hc.keybind(mod+shift+'r','reload')
    hc.keybind(mod+shift+'e','quit')
    hc.keybind(mod+enter,'spawn xterm')
    hc.keybind(mod+'d','spawn dmenu_run')

    hc.keybind('XF86AudioRaiseVolume','spawn amixer -q set Master 5%+')
    hc.keybind('XF86AudioLowerVolume','spawn amixer -q set Master 5%-')
    hc.keybind('XF86AudioMute','spawn amixer -q set Master toggle')
    hc.keybind('XF86MonBrightnessUp','spawn xbacklight +5')
    hc.keybind('XF86MonBrightnessDown','spawn xbacklight -5')

    hc.keybind(mod+'h','focus left')
    hc.keybind(mod+'l','focus right')
    hc.keybind(mod+'j','focus down')
    hc.keybind(mod+'k','focus up')

    hc.keybind(mod+shift+'h','shift left')
    hc.keybind(mod+shift+'l','shift right')
    hc.keybind(mod+shift+'j','shift down')
    hc.keybind(mod+shift+'k','shift up')

    hc.keybind(mod+control+'space','split explode')
    hc.keybind(mod+'u','split bottom 0.5')
    hc.keybind(mod+'o','split right 0.5')

    resizestep=0.05
    hc.keybind(mod+control+'h','resize left +'+str(resizestep))
    hc.keybind(mod+control+'l','resize right +'+str(resizestep))
    hc.keybind(mod+control+'j','resize down +'+str(resizestep))
    hc.keybind(mod+control+'k','resize up +'+str(resizestep))

    hc.keybind(mod+'r','remove')
    hc.keybind(mod+'space','cycle_layout')
    hc.keybind(mod+'s','floating toggle')
    hc.keybind(mod+'f','fullscreen toggle')
    hc.keybind(mod+'p','pseudotile toggle')

    hc.keybind(mod+tab,'cycle_all +1')
    hc.keybind(mod+shift+tab,'cycle_all -1')
    hc.keybind(mod+'c','cycle')
    hc.keybind(mod+'i','jumpto urgent')

    #skipping the tag stuff starting at line 86 of the autostart.sh
    for i in range(1,10):
        hc.add(str(i))
        hc.keybind(mod+str(i),'use_index '+str(i-1))
    #ditch the 'default' tag
    #unfortunately, this will have the side effect of switching to
    #the tag at the second index position, needs to be fixed
    hc.use_index(1)
    hc.merge_tag('default','1')

    #skipping the mouse stuff from line 98 in autostart.sh
    #i don't really get how the mouse works tbh, so just leave it out
    hc.mouseunbind('all')

    #reset floating and tiling themes
    hc.attr(path='theme.tiling.reset',new_value='1')
    hc.attr(path='theme.floating.reset',new_value='1')

    #okay now the theme
    hc.attr(path='theme.background_color',new_value='#1e1e27')

    hc.attr(path='theme.normal.color',new_value='#cfbfad')
    hc.attr(path='theme.inner_color',new_value='#1e1e27')
    hc.attr(path='theme.outer_color',new_value='#1e1e27')

    hc.attr(path='theme.floating.outer_color',new_value='#1e1e27')

    #hc.attr(path='theme.active.color',new_value='#c080d0')
    hc.attr(path='theme.active.color',new_value='#808bed')
   
    hc.attr(path='theme.urgent.color',new_value='#f0ad6d')

    hc.attr(path='theme.border_width',new_value=3)
    hc.attr(path='theme.inner_width',new_value=1)
    hc.attr(path='theme.outer_width',new_value=1)

    hc.attr(path='theme.floating.border_width',new_value=4)
    hc.attr(path='theme.floating.inner_width',new_value=1)
    hc.attr(path='theme.floating.outer_width',new_value=1)

    #rule stuff needs to be filled in here. from line 144

    #all done, unlock and let her rip
    hc.unlock()

    #set tree_style '╾│ ├└╼─┐'

subprocess.call(['xli','-onroot','Wallpapers/good-morning.jpg'])
subprocess.call(['xset','-dpms','s','off'])
subprocess.call(['xrdb','.Xresources'])
